package dns_checks

import (
	"fmt"
	"strings"

	"github.com/fatih/color"
)

func HelpFunc() {
	title := color.New(color.FgHiCyan, color.Bold)
	cmd := color.New(color.FgHiGreen, color.Bold)
	desc := color.New(color.FgYellow)
	section := color.New(color.FgHiMagenta, color.Bold)

	fmt.Println()
	title.Println("Domain Analyzer - DNS Information & Security Tool")
	fmt.Println()
	cmd.Println(strings.Repeat("-", 90))

	section.Println("USAGE:")
	fmt.Println("  domain_analyzer <domain>                    Run full domain analysis")
	fmt.Println("  domain_analyzer [OPTIONS] <domain> [ARGS]   Run specific checks")
	fmt.Println()

	cmd.Println(strings.Repeat("-", 90))
	section.Println("OPTIONS:")
	cmd.Print(" -a                ")
	desc.Println("Check A record")
	cmd.Print(" -c, --cpanel-os   ")
	desc.Println("List cPanel supported OS versions")
	cmd.Print("     --eol         ")
	desc.Println("Show only EOL OS versions (use with --cpanel-os)")
	cmd.Print(" -d, --dns         ")
	desc.Println("Custom Dns Resolver")
	cmd.Print(" -h, --help        ")
	desc.Println("Show help")
	cmd.Print(" -i, --ip          ")
	desc.Println("Get IP information")
	cmd.Print(" -l, --license-check")
	fmt.Println()
	cmd.Print("                   ")
	desc.Println("Check cPanel license for IP")
	cmd.Print(" -m, --mx          ")
	desc.Println("MX record check")
	cmd.Print(" -n, --nmap        ")
	desc.Println("Run nmap port scan on domain")
	cmd.Print("     --ns          ")
	desc.Println("NS record check")
	cmd.Print(" -p, --port=value  ")
	desc.Println("Check single port on domain")
	cmd.Print("     --ports       ")
	desc.Println("Port list")
	cmd.Print(" -r, --rdap        ")
	desc.Println("Get RDAP/Whois information")
	cmd.Print("     --ssl         ")
	desc.Println("Verify SSL certificate")
	cmd.Print(" -x, --ptr         ")
	desc.Println("PTR record check")
	cmd.Println(strings.Repeat("-", 90))
	section.Println("EXAMPLES:")
	cmd.Print("  domain_analyzer   example.com                      ")
	desc.Println("Full analysis of example.com")
	cmd.Print("  domain_analyzer   https://example.com              ")
	desc.Println("URL is automatically parsed to domain")
	cmd.Print("  domain_analyzer   -a example.com                   ")
	desc.Println("Check A record for example.com")
	cmd.Print("  domain_analyzer   -m example.com                   ")
	desc.Println("Check MX records for example.com")
	cmd.Print("  domain_analyzer   -n example.com                   ")
	desc.Println("Port scan example.com")
	cmd.Print("  domain_analyzer   --ns example.com                 ")
	desc.Println("Check NS records for example.com")
	cmd.Print("  domain_analyzer   -p 443 example.com               ")
	desc.Println("Check port 443 on example.com")
	cmd.Print("  domain_analyzer   --ports 80,443,8080 example.com  ")
	desc.Println("Check specific ports on example.com")
	cmd.Print("  domain_analyzer   -x 142.250.187.110               ")
	desc.Println("Check PTR record for IP 142.250.187.110")
	cmd.Print("  domain_analyzer   -i 142.250.187.110               ")
	desc.Println("Check IP info from ipinfo.io (142.250.187.110 google IP)")
	cmd.Print("  domain_analyzer   -i myip                          ")
	desc.Println("Check IP your Public IP")
	cmd.Print("  domain_analyzer   -l 192.168.1.1                   ")
	desc.Println("Check cPanel/WHM license status on given IP")
	cmd.Print("  domain_analyzer   --ssl example.com                ")
	desc.Println("Verify SSL certificate of example.com")
	cmd.Print("  domain_analyzer   -r example.com                   ")
	desc.Println("Retrieve RDAP/WHOIS info for example.com")
	cmd.Print("  domain_analyzer   -d example.com 8.8.8.8           ")
	desc.Println("Query example.com using Google DNS (8.8.8.8)")
	cmd.Print("  domain_analyzer   --cpanel-os                     ")
	desc.Println("List all cPanel supported OS versions")
	cmd.Print("  domain_analyzer   --cpanel-os Ubuntu              ")
	desc.Println("List cPanel OS versions for Ubuntu family")
	cmd.Print("  domain_analyzer   --cpanel-os --eol               ")
	desc.Println("List only EOL OS versions")
	cmd.Print("  domain_analyzer   -c CentOS --eol                 ")
	desc.Println("List EOL CentOS versions")
	desc.Println("  You can enter either 'example.com' or 'https://example.com'.")
	fmt.Println()
}
