package dns_checks

import (
	"fmt"

	"github.com/fatih/color"
)

func HelpFunc() {
	title := color.New(color.FgHiCyan, color.Bold)
	cmd := color.New(color.FgHiGreen, color.Bold)
	desc := color.New(color.FgYellow)
	section := color.New(color.FgHiMagenta, color.Bold)

	fmt.Println()
	title.Println("Domain Analyzer - DNS Information & Security Tool")
	fmt.Println()

	section.Println("USAGE:")
	fmt.Println("  domain_analyzer <domain>                    Run full domain analysis")
	fmt.Println("  domain_analyzer [OPTIONS] <domain> [ARGS]   Run specific checks")
	fmt.Println()

	section.Println("OPTIONS:")
	cmd.Printf("  -h, --help\n\t \\__ ")
	desc.Println("Show help")
	fmt.Println()
	cmd.Printf("  -a <domain>\n\t \\__ ")
	desc.Println("Check A record for domain")
	fmt.Println()
	cmd.Printf("  -i, --ip <IP>\n\t \\__ ")
	desc.Println("Get IP information")
	fmt.Println()
	cmd.Printf("  -l, --license-check <IP>\n\t \\__ ")
	desc.Println("Check cPanel license for IP")
	fmt.Println()
	cmd.Printf("  -m, --mx <domain>\n\t \\__ ")
	desc.Println("Check MX records for domain")
	fmt.Println()
	cmd.Printf("  -n, --nmap <domain>\n\t \\__ ")
	desc.Println("Run nmap port scan on domain")
	fmt.Println()
	cmd.Printf("  --ns <domain>\n\t \\__ ")
	desc.Println("Check NS records for domain")
	fmt.Println()
	cmd.Printf("  -p, --port=<port> <domain>\n\t \\__ ")
	desc.Println("Check single port on domain")
	fmt.Println()
	cmd.Printf("  --ports <port-list> <domain/IP>\n\t \\__ ")
	desc.Println("Check specific ports (comma-separated)")
	fmt.Println()
	cmd.Printf("  -r, --rdap <domain>\n\t \\__ ")
	desc.Println("Get RDAP/Whois information")
	fmt.Println()
	cmd.Printf("  -x, --ptr <IP>\n\t \\__ ")
	desc.Println("PTR (reverse DNS) record check")
	fmt.Println()
	cmd.Printf("  --ssl <domain>\n\t \\__ ")
	desc.Println("Verify SSL certificate")
	fmt.Println()
	cmd.Printf("  -d, --dns <domain> <dns-server>\n\t \\__ ")
	desc.Println("Query domain using custom DNS resolver")
	fmt.Println()
	fmt.Println("  • CNAME Records Lookup")
	fmt.Println("  • IP Info (Geolocation, ISP, etc.)")
	fmt.Println("  • PTR (Reverse DNS) Lookup")
	fmt.Println("  • SSL Certificate Validation")
	fmt.Println("  • RDAP/WHOIS Data Retrieval")
	fmt.Println("  • Cloudflare Detection & Real IP Discovery")
	fmt.Println("  • cPanel License Check")
	fmt.Println("  • Port Scanning")
	fmt.Println()

	section.Println("EXAMPLES:")
	cmd.Print("  domain_analyzer   example.com                      ")
	desc.Println("Full analysis of example.com")
	cmd.Print("  domain_analyzer   https://example.com              ")
	desc.Println("URL is automatically parsed to domain")
	cmd.Print("  domain_analyzer   -a example.com                   ")
	desc.Println("Check A record for example.com")
	cmd.Print("  domain_analyzer   -m example.com                   ")
	desc.Println("Check MX records for example.com")
	cmd.Print("  domain_analyzer   -n example.com                   ")
	desc.Println("Port scan example.com")
	cmd.Print("  domain_analyzer   --ns example.com                 ")
	desc.Println("Check NS records for example.com")
	cmd.Print("  domain_analyzer   -p 443 example.com               ")
	desc.Println("Check port 443 on example.com")
	cmd.Print("  domain_analyzer   --ports 80,443,8080 example.com  ")
	desc.Println("Check specific ports on example.com")
	cmd.Print("  domain_analyzer   -x 142.250.187.110               ")
	desc.Println("Check PTR record for IP 142.250.187.110")
	cmd.Print("  domain_analyzer   -i 142.250.187.110               ")
	desc.Println("Check IP info from ipinfo.io (142.250.187.110 google IP)")
	cmd.Print("  domain_analyzer   -l 192.168.1.1                   ")
	desc.Println("Check cPanel/WHM license status on given IP")
	cmd.Print("  domain_analyzer   --ssl example.com                ")
	desc.Println("Verify SSL certificate of example.com")
	cmd.Print("  domain_analyzer   -r example.com                   ")
	desc.Println("Retrieve RDAP/WHOIS info for example.com")
	cmd.Print("  domain_analyzer   -d example.com 8.8.8.8           ")
	desc.Println("Query example.com using Google DNS (8.8.8.8)")
	desc.Println("  You can enter either 'example.com' or 'https://example.com'.")
	fmt.Println()
}
