package dns_checks

import (
	"fmt"

	"github.com/fatih/color"
)

func HelpFunc() {
	title := color.New(color.FgHiCyan, color.Bold)
	cmd := color.New(color.FgHiGreen, color.Bold)
	desc := color.New(color.FgYellow)
	section := color.New(color.FgHiMagenta, color.Bold)

	fmt.Println()
	title.Println("Domain Analyzer - DNS Information & Security Tool")
	fmt.Println()

	section.Println("USAGE:")
	fmt.Println("  domain_analyzer <domain>                    Run full domain analysis")
	fmt.Println("  domain_analyzer [OPTIONS] <domain> [ARGS]   Run specific checks")
	fmt.Println()

	section.Println("OPTIONS:")
	cmd.Printf("  -h, --help\n\t \\__ ")
	desc.Println("Show help")
	fmt.Println()
	cmd.Printf("  -i, --ip <IP>\n\t \\__ ")
	desc.Println("Get IP information")
	fmt.Println()
	cmd.Printf("  -l, --license-check <IP>\n\t \\__ ")
	desc.Println("Check cPanel license for IP")
	fmt.Println()
	cmd.Printf("  -n, --nmap <domain>\n\t \\__ ")
	desc.Println("Run nmap port scan on domain")
	fmt.Println()
	cmd.Printf("  -r, --rdap <domain>\n\t \\__ ")
	desc.Println("Get RDAP/Whois information")
	fmt.Println()
	cmd.Printf("  -s, --single-port=<port> <domain>\n\t \\__ ")
	desc.Println("Check single port on domain")
	fmt.Println()
	cmd.Printf("  --ssl <domain>\n\t \\__ ")
	desc.Println("Verify SSL certificate")
	fmt.Println()

	section.Println("FEATURES:")
	fmt.Println("  • IP Address Resolution")
	fmt.Println("  • MX Records Lookup")
	fmt.Println("  • TXT Records Lookup")
	fmt.Println("  • NS Records Lookup")
	fmt.Println("  • CNAME Records Lookup")
	fmt.Println("  • IP Info (Geolocation, ISP, etc.)")
	fmt.Println("  • PTR (Reverse DNS) Lookup")
	fmt.Println("  • SSL Certificate Validation")
	fmt.Println("  • RDAP/WHOIS Data Retrieval")
	fmt.Println("  • Cloudflare Detection & Real IP Discovery")
	fmt.Println("  • cPanel License Check")
	fmt.Println("  • Port Scanning")
	fmt.Println()

	section.Println("EXAMPLES:")
	cmd.Print("  domain_analyzer example.com            ")
	desc.Println("Full analysis of example.com")
	cmd.Print("  domain_analyzer https://example.com    ")
	desc.Println("URL is automatically parsed to domain")
	cmd.Print("  domain_analyzer -n example.com         ")
	desc.Println("Port scan example.com")
	cmd.Print("  domain_analyzer -s 443 example.com     ")
	desc.Println("Check port 443 on example.com")
	cmd.Print("  domain_analyzer -i 142.250.187.110     ")
	desc.Println("Check IP info from ipinfo.io (142.250.187.110 google IP)")
	cmd.Print("  domain_analyzer -l 192.168.1.1         ")
	desc.Println("Check cPanel/WHM license status on given IP")
	cmd.Print("  domain_analyzer --ssl example.com      ")
	desc.Println("Verify SSL certificate of example.com")
	cmd.Print("  domain_analyzer -r example.com         ")
	desc.Println("Retrieve RDAP/WHOIS info for example.com")
	fmt.Println()

	section.Println("NOTE:")
	desc.Println("  URLs with http:// or https:// prefixes are automatically stripped.")
	desc.Println("  You can enter either 'example.com' or 'https://example.com'.")
	fmt.Println()
}
